services:
  # 1. Backend (Node.js API)
  - type: web
    name: felicity-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://salesangameshwar1_db_user:felicity@123@cluster0.tf9t0ts.mongodb.net/felicity?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://felicity-iiit.vercel.app # Replace with your actual Vercel URL
      - key: CACHEX_HOST
        value: cachex-engine
      - key: CACHEX_PORT
        value: 6379

  # 2. CacheX Engine (C++ TCP Server)
  - type: pserv
    name: cachex-engine
    env: docker
    rootDir: cachex
    envVars:
      - key: PORT
        value: 6379
