services:
  - type: web
    name: felicity-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CACHEX_HOST
        value: cachex-engine
      - key: CACHEX_PORT
        value: 6379
