services:
  # 1. Monolithic Web Service (Node API + CacheX)
  - type: web
    name: felicity-backend
    env: docker
    rootDir: .
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://salesangameshwar1_db_user:felicity@123@cluster0.tf9t0ts.mongodb.net/felicity?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://felicity-iiit.vercel.app # Replace with your actual Vercel URL
      - key: CACHEX_HOST
        value: 127.0.0.1
      - key: CACHEX_PORT
        value: 6379
