const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

/**
 * Send event registration ticket via email
 */
const sendTicketEmail = async ({ to, participantName, eventName, ticketId, qrCodeBase64, eventDate, venue }) => {
  const mailOptions = {
    from: `"Felicity Events" <${process.env.EMAIL_USER}>`,
    to,
    subject: `🎟️ Your Ticket for ${eventName} - Felicity`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #f9fafb; padding: 24px; border-radius: 12px;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 24px; border-radius: 8px; text-align: center; margin-bottom: 24px;">
          <h1 style="color: white; margin: 0; font-size: 28px;">🎪 Felicity</h1>
          <p style="color: rgba(255,255,255,0.85); margin: 8px 0 0 0;">Event Management System</p>
        </div>
        
        <div style="background: white; padding: 24px; border-radius: 8px; margin-bottom: 16px;">
          <h2 style="color: #1f2937; margin-top: 0;">Hello, ${participantName}! 👋</h2>
          <p style="color: #6b7280;">You have successfully registered for:</p>
          <h3 style="color: #667eea; font-size: 22px;">${eventName}</h3>
          <p style="color: #6b7280;"><strong>📅 Date:</strong> ${eventDate}</p>
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;">
          <p style="color: #374151;"><strong>🎫 Ticket ID:</strong> <code style="background: #f3f4f6; padding: 4px 8px; border-radius: 4px; font-family: monospace;">${ticketId}</code></p>
          <p style="color: #6b7280; font-size: 14px;">Show this QR code at the event entrance:</p>
          <div style="text-align: center; margin: 16px 0;">
            <img src="cid:qrcode" alt="QR Code" style="width: 200px; height: 200px; border: 4px solid #667eea; border-radius: 8px;"/>
          </div>
        </div>
        
        <p style="color: #9ca3af; font-size: 12px; text-align: center;">This ticket was generated by Felicity Event Management System. Do not share this QR code.</p>
      </div>
    `,
    attachments: [{
      filename: 'ticket-qr.png',
      content: qrCodeBase64.split('base64,')[1],
      encoding: 'base64',
      cid: 'qrcode'
    }]
  };

  await transporter.sendMail(mailOptions);
};

/**
 * Send organizer credentials email (from admin)
 */
const sendOrganizerCredentials = async ({ to, organizerName, loginEmail, password }) => {
  const mailOptions = {
    from: `"Felicity Admin" <${process.env.EMAIL_USER}>`,
    to,
    subject: '🔑 Your Felicity Organizer Account Credentials',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
        <h2>Welcome to Felicity, ${organizerName}!</h2>
        <p>Your organizer account has been created by the Admin. Here are your login credentials:</p>
        <div style="background: #f3f4f6; padding: 16px; border-radius: 8px; margin: 16px 0;">
          <p><strong>Email:</strong> ${loginEmail}</p>
          <p><strong>Password:</strong> ${password}</p>
        </div>
        <p style="color: #ef4444;">⚠️ Please change your password after your first login.</p>
        <p>Login at: <a href="${process.env.CLIENT_URL}/login">Felicity Login</a></p>
      </div>
    `
  };

  await transporter.sendMail(mailOptions);
};

/**
 * Send password reset notification to organizer
 */
const sendPasswordResetEmail = async ({ to, organizerName, newPassword }) => {
  const mailOptions = {
    from: `"Felicity Admin" <${process.env.EMAIL_USER}>`,
    to,
    subject: '🔒 Your Password Has Been Reset - Felicity',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
        <h2>Password Reset - ${organizerName}</h2>
        <p>Your password reset request has been approved by the Admin.</p>
        <div style="background: #f3f4f6; padding: 16px; border-radius: 8px; margin: 16px 0;">
          <p><strong>New Password:</strong> ${newPassword}</p>
        </div>
        <p style="color: #ef4444;">⚠️ Please change this password after logging in.</p>
      </div>
    `
  };

  await transporter.sendMail(mailOptions);
};

module.exports = { sendTicketEmail, sendOrganizerCredentials, sendPasswordResetEmail };
